Tiktaktoe/Tiktaktoe/Models/ErrorViewModel.cs
namespace Tiktaktoe.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tiktaktoe/Tiktaktoe/Models/Player.cs
using System.ComponentModel.DataAnnotations;
using Tiktaktoe.Data.EnumsData;

namespace Tiktaktoe.Models
{
    public class Player
    {
        [Key]
        public string Name { get; set; }
        public string OpponentName { get; set; }
        public bool IsOpponentVirtual { get; set; }
        public GameMode GameMode { get; set; }
        public string GameDuration { get; set; }
        public int Wins { get; set; }
        public int Loses { get; set; }
        public int Draws { get; set; }
        public int Score { get; set; }


    }
}

Tiktaktoe/Tiktaktoe/Models/PlayerModel.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using Tiktaktoe.Data.EnumsData;

namespace Tiktaktoe.Models
{
    public class PlayerModel
    {
        [Key]
        public string Name { get; set; }
        public string OpponentName { get; set; }
        public string GameDuration { get; set; }
        public string GridSize { get; set; }

        public GameMode GameMode { get; set; }
        
        public int Wins { get; set; }
        public int Loses { get; set; }
        public int Draws { get; set; }
        public int Score { get; set; }
        public bool isOpponentVirtual { get; set; }

    }
}

Tiktaktoe/Tiktaktoe/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tiktaktoe.Models;

namespace Tiktaktoe.Controllers
{

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public string[] GridSizes = new[] { "3 x 3", "5 x 5" };
        public string[] selectedOpponent = new[] { "A friend", "A Bot" };
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var gridSizes = new[]
            {
                "3 x 3",
                "5 x 5"
            };
            var opponentTypes = new[]
            {
                "A friend",
                "A bot"
            };
            ViewData[nameof(gridSizes)] = gridSizes;
            ViewData[nameof(opponentTypes)] = opponentTypes;
            return View();
        }
        [HttpPost]
        public IActionResult GamePage()
        {   
            PlayerModel player = new PlayerModel();
            return View(player);
        }
        public IActionResult Privacy(EventArgs e)
        {
            Console.WriteLine(e.ToString());
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tiktaktoe/Tiktaktoe/ViewComponents/ClassicMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Tiktaktoe.Models;

namespace Tiktaktoe.ViewComponents
{
    public class ClassicMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            PlayerModel player = new PlayerModel();
            return View(player);
        }
    }
}

Tiktaktoe/Tiktaktoe/ViewComponents/JoinAFriendViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tiktaktoe.ViewComponents
{
    public class JoinAFriendViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Tiktaktoe/Tiktaktoe/ViewComponents/MainMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tiktaktoe.ViewComponents
{
    public class MainMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Tiktaktoe/Tiktaktoe/ViewComponents/SettingsViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace Tiktaktoe.ViewComponents
{
    public class SettingsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Tiktaktoe/Tiktaktoe/Views/Home/GamePage.cshtml
@{
    ViewData["Title"] = "GamePage";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Tiktaktoe/Tiktaktoe/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="main-menu">
    @await Component.InvokeAsync("MainMenu")
</div>

<div id="classic-menu">
    @await Component.InvokeAsync("ClassicMenu")
</div>
<div id="join-menu">
    @await Component.InvokeAsync("JoinAFriend")
</div>
<div id="settings">
    @await Component.InvokeAsync("Settings")
</div>

Tiktaktoe/Tiktaktoe/Views/Shared/Components/ClassicMenu/Default.cshtml
@model PlayerModel

<div class="py-3 titles text-center">
    <h2 class="game_font"> New Classic Game </h2>
</div>

<div class="w-100 text-center">
    <form asp-controller = "HomeController" method="post" class=" d-flex flex-column gap-5 justify-content-around align-items-center">
        <div id="nickname" class="d-flex flex-column align-items-center justify-content-around">
            <label class="game_font">Enter your nickname</label>
            <input required asp-for=Name type="text"/>
        </div>
        <div id="gridSize">
            <fieldset >
                <legend class="game_font">select your grid size</legend>
                <div class="d-flex align-items-center justify-content-around">
                @foreach (var gridSize in ViewBag.GridSizes)
                { 
                        <div class="d-flex flex-column align-items-center justify-content-center">
                            <label class="game_font">@gridSize</label>
                            <input required asp-for=GridSize type="radio" id="gridSize" name="size" value=@gridSize />
                        </div>
                }
                </div>
            </fieldset>
            

        </div>
        <div id="opponentChoice">
            <fieldset>
                <legend class="game_font">who is going to be your opponent</legend>
                <div class="d-flex align-items-center justify-content-around">
                    @foreach (var opponent in ViewBag.OpponentTypes)
                    {
                        <div class="d-flex flex-column align-items-center justify-content-center">
                            <label class="game_font">@opponent</label>
                            <input required type="radio" id="opponent" name="opponent" value=@opponent />
                        </div>
                    }
                </div>

            </fieldset>
        </div>
        <div id="specialMode" class=" w-75 text-center  d-flex  align-items-center justify-content-around">
            <button class="fw-bolder btn menu_buttons game_font" type="button" onclick="backToMainMenu('classic-menu')"> Back </button>
            <button class="fw-bolder btn menu_buttons game_font" asp-action="GamePage" type="submit"> Continue </button>
        </div>
   </form>
</div>

Tiktaktoe/Tiktaktoe/Views/Shared/Components/JoinAFriend/Default.cshtml
<div class="py-3 titles text-center">
    <h2 class="game_font"> Join A Friend! </h2>
</div>

<div class="w-100 d-flex flex-column gap-4 justify-content-around align-items-center">
    Here will be the teh settings to join a friend
</div>

Tiktaktoe/Tiktaktoe/Views/Shared/Components/MainMenu/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="py-3 titles text-center">
    <h2 class="game_font"> Game Menu </h2>
</div>

<div class="w-100 d-flex flex-column gap-4 justify-content-around align-items-center">
    <button class="fw-bolder btn menu_buttons game_font" type="button" onclick="openAMenu('classic-menu')"> Classic </button>
    <button class="fw-bolder btn menu_buttons game_font" type="button" onclick="openAMenu('join-menu')"> Join a friend </button>
    <button class="fw-bolder btn menu_buttons game_font" type="button"> Best scores </button>
    <button class=" mt-5 fw-bolder btn menu_buttons game_font" type="button" onclick="openAMenu('settings')"> Settings </button>
</div>

Tiktaktoe/Tiktaktoe/Views/Shared/Components/Settings/Default.cshtml
<div class="py-3 titles text-center">
    <h2 class="game_font"> Settings </h2>
</div>

<div class="w-100 d-flex flex-column gap-4 justify-content-around align-items-center">
    Here will be the Settings  buttons and things
</div>

Tiktaktoe/Tiktaktoe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tiktaktoe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tiktaktoe.styles.css" asp-append-version="true" />
</head>
<body onload="getRandomPositions()">
    <header>
        <div class="container-fluid border d-flex modal-header border-0">
            <h3 class="m-0 game_font display-6 fw-bold titles"> TIX TAX TOE</h3>
            <a class="display-6 text-decoration-none fw-bold fst-italic titles" href="https://nbj-dev.me" target="_blank">N.B.J.</a>
        </div>
    </header>
    <div class="titles game_font display-4" id="random_x"> X </div>
    <div class="titles game_font display-4" id="random_o"> O </div>
    <div class="container">
        <main role="main" class="pb-3">
            <div class=" mt-2 container game-container">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="footer text-muted ">
        <div class="container text-center titles">
            &copy; nbj-dev 2023 - Tiktaktoe
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/mainMenu.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>